// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcxywcglxmykopjutguu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjeHl3Y2dseG15a29wanV0Z3V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODkyOTQsImV4cCI6MjA1OTc2NTI5NH0.6qGYcR2AgzCyNfZXWCd0-SOOz8FMkmF9YXwWJjZ5CuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);